version: "3"
services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_PASSWORD=${APP_PASSWORD}
    networks:
      - reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bin.rule=Host(`bin.grasslabs.dev`)"
      - "traefik.http.routers.bin.entrypoints=web,websecure"
      - "traefik.http.routers.bin.tls.certresolver=myresolver"
      - "traefik.http.services.bin.loadbalancer.server.port=8000"
      - "traefik.docker.network=reverse_proxy"
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
